### ISSUE TITLE
Update AWS Well Architected Framework PDF Link

### ISSUE THREAD

**Issue by h3ct0rjs** [keenanromain/AWS-SAA-C02-Study-Guide#8]
Hi @keenanromain, 

It seems like the well architected pdf has been updated, you could check that in the following url https://docs.aws.amazon.com/wellarchitected/latest/framework/wellarchitected-framework.pdf 

Thanks in advance for the Study Guide.
Sincerely, 
H, 
Colombia

**Comment by keenanromain** [comment]
Gracias Hector. Haré el cambio ahora
